name: seaice_ecdr
channels:
  - conda-forge
  - nsidc
  - nodefaults
dependencies:
  - python ~=3.10.0

  ########################################
  # Imported dependencies and extensions #
  ########################################
  - numpy >=2.2.6
  - xarray  >=2025.6.1
  - dask 
  - netCDF4 >=1.7.2
  - loguru >=0.7.3
  - scipy
  # Required for aggregating NC files (provides the `ncrcat` CLI)
  - nco
  - pandas
  - opencv
  - pm_tb_data ~=0.5.0
  - pm_icecon ~=0.6.0
  - leafmap
  - rioxarray
  - hvplot
  - jupyter_bokeh
  - h5netcdf

  #############################
  # Non-imported dependencies #
  #############################

  # testing/linting/typechecking
  - pre-commit
  - pytest
  - pytest-cov
  - mypy
  - pyfakefs
  - pytest-order
  # required by leafmap
  - localtileserver

  # other utilities
  - bump-my-version
  - ipython
  - ipdb
  - conda-lock
  - invoke
