name: seaice_ecdr
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python ~=3.10.0

  ########################################
  # Imported dependencies and extensions #
  ########################################
  - numpy ~=1.22.4
  - xarray ~=2023.6
  - netCDF4 ~=1.6.3
  - loguru ~=0.7
  - scipy ~=1.11.3
  - seaice ~=6.0

  #############################
  # Non-imported dependencies #
  #############################

  # testing/linting/typechecking
  - pre-commit
  - pytest ~=7.1
  - mypy ~=1.5.1

  # other utilities
  - bump-my-version ~=0.10.0
  - ipython
  - ipdb
  - conda-lock
