name: seaice_ecdr
channels:
  - conda-forge
  - nsidc
  - nodefaults
dependencies:
  - python ~=3.10.0

  ########################################
  # Imported dependencies and extensions #
  ########################################
  - numpy ~=2.2.6
  - xarray  >=2025.6.1
  - dask >=2025.7.0
  - netCDF4 ~=1.7
  - loguru >=0.7.3
  - scipy ~=1.15
  # Required for aggregating NC files (provides the `ncrcat` CLI)
  - nco >=5.3.4
  - pandas ~=2.3
  - opencv ~=4.12
  - pm_tb_data ~=0.5.0
  - pm_icecon ~=0.6.0
  - rioxarray ~=1.4

  #############################
  # Non-imported dependencies #
  #############################

  # testing/linting/typechecking
  - pre-commit
  - pytest
  - pytest-cov
  - mypy
  - pyfakefs
  - pytest-order
  # required by leafmap
  - localtileserver

  # other utilities
  - bump-my-version
  - ipython
  - ipdb
  - conda-lock
  - invoke
