name: seaice_ecdr
channels:
  - conda-forge
  - nsidc
  - nodefaults
dependencies:
  - python ~=3.10.0

  ########################################
  # Imported dependencies and extensions #
  ########################################
  - numpy ~=1.22.4
  - xarray ~=2023.6
  - dask ~=2023.10.1
  - netCDF4 ~=1.6.5
  - loguru ~=0.7
  - scipy ~=1.8.1
  # Required for aggregating NC files (provides the `ncrcat` CLI)
  - nco ~5.1.9
  - pandas ~=1.4.4

  #############################
  # Non-imported dependencies #
  #############################

  # testing/linting/typechecking
  - pre-commit
  - pytest ~=7.1
  - pytest-cov ~=4.1.0
  - mypy ==1.7.0
  - pyfakefs ~=5.2.4
  - pytest-order ~=1.0.1

  # other utilities
  - bump-my-version ~=0.10.0
  - ipython
  - ipdb
  - conda-lock
  - invoke
