# The information here was originally adapted from CDRv4's config file:
#     missing_ranges.yml
#
# Date ranges specified here are assumed not to have valid tb inputs for the
#   specified platform
treat_tbs_as_missing:
  n07:
    north:
      # These Tbs are corrupt with obvious “checkerboarding”
      - ['1984-07-03', '1984-08-04']
      # Bad input data
      - ['1986-12-04', '1986-12-10']
    south:
      # Bad input data
      - ['1986-12-04', '1986-12-10']
  F17:
    south:
      # Bad input data
      - ['2008-03-24', '2008-03-25']
      # Bad input data
      - ['2015-08-06', '2015-08-06']
  am2:
    north:
      # Bad TB field(s)
      - ['2018-12-16', '2018-12-16']
    south:
      # Bad TB field(s)
      - ['2018-12-16', '2018-12-16']

# Date ranges specified here have outputs that are all missing (255).
treat_outputs_as_missing:
  n07:
    north:
      # These Tbs are corrupt with obvious “checkerboarding”
      - ['1984-07-03', '1984-08-04']
      # No SMMR data between 8/11 and 8/25 1984
      - ['1984-08-12', '1984-08-24']
      # Bad input data
      - ['1986-12-04', '1986-12-10']
    south:
      # No SMMR data between 8/11 and 8/25 1984
      - ['1984-08-12', '1984-08-24']
      # No SH TBS for 8/5-8/9
      - ['1985-08-05', '1985-08-09']
      # Bad input data
      - ['1986-12-04', '1986-12-10']
  F08:
    north:
      # Large missing data gap due to satellite issues
      - ['1987-12-03', '1988-01-13']
      # Missing data
      - ['1990-12-26', '1990-12-27']
    south:
      # Large missing data gap due to satellite issues
      - ['1987-12-03', '1988-01-13']
